"""Standardized machine-readable error codes for cross-platform internationalization."""

from enum import StrEnum


class ErrorCode(StrEnum):
    """Categorized application error codes."""

    # Generic & System
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
    BAD_REQUEST = "BAD_REQUEST"
    NOT_FOUND = "NOT_FOUND"
    CONFLICT = "CONFLICT"
    DATABASE_ERROR = "DATABASE_ERROR"

    # Authentication & Authorization
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    AUTH_INVALID_TOKEN = "AUTH_INVALID_TOKEN"
    AUTH_EXPIRED_TOKEN = "AUTH_EXPIRED_TOKEN"
    AUTH_INVALID_OTP = "AUTH_INVALID_OTP"
    AUTH_OTP_EXPIRED = "AUTH_OTP_EXPIRED"
    AUTH_PHONE_REQUIRED = "AUTH_PHONE_REQUIRED"

    # Validation & Payload
    VALIDATION_ERROR = "VALIDATION_ERROR"
    INVALID_REQUEST_BODY = "INVALID_REQUEST_BODY"
    INVALID_PARAMETERS = "INVALID_PARAMETERS"

    # Business Rules
    BUSINESS_RULE_VIOLATION = "BUSINESS_RULE_VIOLATION"
    RESOURCE_ALREADY_EXISTS = "RESOURCE_ALREADY_EXISTS"
    OPERATION_NOT_PERMITTED = "OPERATION_NOT_PERMITTED"
