"""Standardized machine-readable error codes for cross-platform internationalization."""

from enum import StrEnum


class ErrorCode(StrEnum):
    """Categorized application error codes."""

    # Generic & System
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
    BAD_REQUEST = "BAD_REQUEST"
    NOT_FOUND = "NOT_FOUND"
    CONFLICT = "CONFLICT"
    DATABASE_ERROR = "DATABASE_ERROR"

    # Authentication & Credentials
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
    AUTH_INVALID_TOKEN = "AUTH_INVALID_TOKEN"
    AUTH_EXPIRED_TOKEN = "AUTH_EXPIRED_TOKEN"
    AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
    AUTH_REFRESH_TOKEN_INVALID = "AUTH_REFRESH_TOKEN_INVALID"
    AUTH_REFRESH_TOKEN_EXPIRED = "AUTH_REFRESH_TOKEN_EXPIRED"
    AUTH_REFRESH_TOKEN_REVOKED = "AUTH_REFRESH_TOKEN_REVOKED"
    AUTH_ACCOUNT_INACTIVE = "AUTH_ACCOUNT_INACTIVE"
    AUTH_ACCOUNT_SUSPENDED = "AUTH_ACCOUNT_SUSPENDED"
    AUTH_UNAUTHORIZED = "AUTH_UNAUTHORIZED"
    AUTH_FORBIDDEN = "AUTH_FORBIDDEN"

    # OTP Operations
    AUTH_INVALID_OTP = "AUTH_INVALID_OTP"
    AUTH_OTP_EXPIRED = "AUTH_OTP_EXPIRED"
    AUTH_OTP_MAX_ATTEMPTS = "AUTH_OTP_MAX_ATTEMPTS"
    AUTH_OTP_RATE_LIMITED = "AUTH_OTP_RATE_LIMITED"
    AUTH_OTP_NOT_FOUND = "AUTH_OTP_NOT_FOUND"
    AUTH_PHONE_REQUIRED = "AUTH_PHONE_REQUIRED"

    # User Management
    USER_NOT_FOUND = "USER_NOT_FOUND"
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
    USER_EMAIL_ALREADY_EXISTS = "USER_EMAIL_ALREADY_EXISTS"
    USER_PHONE_ALREADY_EXISTS = "USER_PHONE_ALREADY_EXISTS"
    USER_ROLE_NOT_ALLOWED = "USER_ROLE_NOT_ALLOWED"

    # Validation & Payload
    VALIDATION_ERROR = "VALIDATION_ERROR"
    INVALID_REQUEST_BODY = "INVALID_REQUEST_BODY"
    INVALID_PARAMETERS = "INVALID_PARAMETERS"

    # Business Rules
    BUSINESS_RULE_VIOLATION = "BUSINESS_RULE_VIOLATION"
    RESOURCE_ALREADY_EXISTS = "RESOURCE_ALREADY_EXISTS"
    OPERATION_NOT_PERMITTED = "OPERATION_NOT_PERMITTED"

    # Therapist Domain
    THERAPIST_NOT_FOUND = "THERAPIST_NOT_FOUND"
    THERAPIST_ALREADY_EXISTS = "THERAPIST_ALREADY_EXISTS"
    THERAPIST_ACCESS_DENIED = "THERAPIST_ACCESS_DENIED"
    INVALID_THERAPIST_STATUS = "INVALID_THERAPIST_STATUS"
    INVALID_STATUS_TRANSITION = "INVALID_STATUS_TRANSITION"
    INVALID_VERIFICATION_STATUS = "INVALID_VERIFICATION_STATUS"
