"""Standardized machine-readable error codes for cross-platform internationalization."""

from enum import StrEnum


class ErrorCode(StrEnum):
    """Categorized application error codes."""

    # Generic & System
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
    BAD_REQUEST = "BAD_REQUEST"
    NOT_FOUND = "NOT_FOUND"
    CONFLICT = "CONFLICT"
    DATABASE_ERROR = "DATABASE_ERROR"

    # Authentication & Credentials
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
    AUTH_INVALID_TOKEN = "AUTH_INVALID_TOKEN"
    AUTH_EXPIRED_TOKEN = "AUTH_EXPIRED_TOKEN"
    AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
    AUTH_REFRESH_TOKEN_INVALID = "AUTH_REFRESH_TOKEN_INVALID"
    AUTH_REFRESH_TOKEN_EXPIRED = "AUTH_REFRESH_TOKEN_EXPIRED"
    AUTH_REFRESH_TOKEN_REVOKED = "AUTH_REFRESH_TOKEN_REVOKED"
    AUTH_ACCOUNT_INACTIVE = "AUTH_ACCOUNT_INACTIVE"
    AUTH_ACCOUNT_SUSPENDED = "AUTH_ACCOUNT_SUSPENDED"
    AUTH_UNAUTHORIZED = "AUTH_UNAUTHORIZED"
    AUTH_FORBIDDEN = "AUTH_FORBIDDEN"

    # OTP Operations
    AUTH_INVALID_OTP = "AUTH_INVALID_OTP"
    AUTH_OTP_EXPIRED = "AUTH_OTP_EXPIRED"
    AUTH_OTP_MAX_ATTEMPTS = "AUTH_OTP_MAX_ATTEMPTS"
    AUTH_OTP_RATE_LIMITED = "AUTH_OTP_RATE_LIMITED"
    AUTH_OTP_NOT_FOUND = "AUTH_OTP_NOT_FOUND"
    AUTH_PHONE_REQUIRED = "AUTH_PHONE_REQUIRED"

    # User Management
    USER_NOT_FOUND = "USER_NOT_FOUND"
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
    USER_EMAIL_ALREADY_EXISTS = "USER_EMAIL_ALREADY_EXISTS"
    USER_PHONE_ALREADY_EXISTS = "USER_PHONE_ALREADY_EXISTS"
    USER_ROLE_NOT_ALLOWED = "USER_ROLE_NOT_ALLOWED"

    # Validation & Payload
    VALIDATION_ERROR = "VALIDATION_ERROR"
    INVALID_REQUEST_BODY = "INVALID_REQUEST_BODY"
    INVALID_PARAMETERS = "INVALID_PARAMETERS"

    # Business Rules
    BUSINESS_RULE_VIOLATION = "BUSINESS_RULE_VIOLATION"
    RESOURCE_ALREADY_EXISTS = "RESOURCE_ALREADY_EXISTS"
    OPERATION_NOT_PERMITTED = "OPERATION_NOT_PERMITTED"

    # Therapist Domain
    THERAPIST_NOT_FOUND = "THERAPIST_NOT_FOUND"
    THERAPIST_ALREADY_EXISTS = "THERAPIST_ALREADY_EXISTS"
    THERAPIST_ACCESS_DENIED = "THERAPIST_ACCESS_DENIED"
    INVALID_THERAPIST_STATUS = "INVALID_THERAPIST_STATUS"
    INVALID_STATUS_TRANSITION = "INVALID_STATUS_TRANSITION"
    INVALID_VERIFICATION_STATUS = "INVALID_VERIFICATION_STATUS"

    # Availability & Scheduling Domain
    AVAILABILITY_NOT_FOUND = "AVAILABILITY_NOT_FOUND"
    INVALID_SCHEDULE_INTERVAL = "INVALID_SCHEDULE_INTERVAL"
    SCHEDULE_OVERLAP = "SCHEDULE_OVERLAP"
    INVALID_DATE_RANGE = "INVALID_DATE_RANGE"
    DATE_IN_PAST = "DATE_IN_PAST"
    EXTRA_SLOT_CONFLICT = "EXTRA_SLOT_CONFLICT"
    EXTRA_SLOT_NOT_FOUND = "EXTRA_SLOT_NOT_FOUND"
    DATE_EXCEPTION_NOT_FOUND = "DATE_EXCEPTION_NOT_FOUND"

    # Booking & Reservation Domain
    BOOKING_NOT_FOUND = "BOOKING_NOT_FOUND"
    BOOKING_ALREADY_EXISTS = "BOOKING_ALREADY_EXISTS"
    BOOKING_SLOT_NOT_FOUND = "BOOKING_SLOT_NOT_FOUND"
    BOOKING_SLOT_UNAVAILABLE = "BOOKING_SLOT_UNAVAILABLE"
    BOOKING_RESERVATION_EXPIRED = "BOOKING_RESERVATION_EXPIRED"
    BOOKING_RESERVATION_NOT_FOUND = "BOOKING_RESERVATION_NOT_FOUND"
    BOOKING_RESERVATION_FORBIDDEN = "BOOKING_RESERVATION_FORBIDDEN"
    BOOKING_INVALID_STATE = "BOOKING_INVALID_STATE"
    BOOKING_CONFLICT = "BOOKING_CONFLICT"
    BOOKING_CANCEL_NOT_ALLOWED = "BOOKING_CANCEL_NOT_ALLOWED"

    # Payment Domain
    PAYMENT_NOT_FOUND = "PAYMENT_NOT_FOUND"
    PAYMENT_ALREADY_PAID = "PAYMENT_ALREADY_PAID"
    PAYMENT_FAILED = "PAYMENT_FAILED"
    PAYMENT_VERIFICATION_FAILED = "PAYMENT_VERIFICATION_FAILED"
    PAYMENT_PROVIDER_ERROR = "PAYMENT_PROVIDER_ERROR"
    PAYMENT_WEBHOOK_INVALID = "PAYMENT_WEBHOOK_INVALID"
    PAYMENT_IDEMPOTENCY_CONFLICT = "PAYMENT_IDEMPOTENCY_CONFLICT"
    PAYMENT_FORBIDDEN = "PAYMENT_FORBIDDEN"

    # Offer & Coupon Domain
    OFFER_NOT_FOUND = "OFFER_NOT_FOUND"
    OFFER_EXPIRED = "OFFER_EXPIRED"
    OFFER_NOT_ACTIVE = "OFFER_NOT_ACTIVE"
    OFFER_USAGE_EXCEEDED = "OFFER_USAGE_EXCEEDED"
    OFFER_USER_LIMIT_REACHED = "OFFER_USER_LIMIT_REACHED"
    OFFER_MINIMUM_ORDER_NOT_MET = "OFFER_MINIMUM_ORDER_NOT_MET"
    OFFER_NOT_APPLICABLE = "OFFER_NOT_APPLICABLE"

    # Package Domain
    PACKAGE_NOT_FOUND = "PACKAGE_NOT_FOUND"
    PACKAGE_EXHAUSTED = "PACKAGE_EXHAUSTED"
    PACKAGE_EXPIRED = "PACKAGE_EXPIRED"
    PACKAGE_INACTIVE = "PACKAGE_INACTIVE"
    PACKAGE_ALREADY_OWNED = "PACKAGE_ALREADY_OWNED"
    PACKAGE_FORBIDDEN = "PACKAGE_FORBIDDEN"

    # Session Domain
    SESSION_NOT_FOUND = "SESSION_NOT_FOUND"
    SESSION_ALREADY_EXISTS = "SESSION_ALREADY_EXISTS"
    SESSION_FORBIDDEN = "SESSION_FORBIDDEN"
    SESSION_INVALID_STATE = "SESSION_INVALID_STATE"
    SESSION_ALREADY_STARTED = "SESSION_ALREADY_STARTED"
    SESSION_ALREADY_COMPLETED = "SESSION_ALREADY_COMPLETED"
    SESSION_START_TOO_EARLY = "SESSION_START_TOO_EARLY"
    SESSION_START_TOO_LATE = "SESSION_START_TOO_LATE"
    SESSION_NOT_READY = "SESSION_NOT_READY"
    SESSION_ATTENDANCE_INVALID = "SESSION_ATTENDANCE_INVALID"
    SESSION_NOTE_FORBIDDEN = "SESSION_NOTE_FORBIDDEN"
    SESSION_NOTE_NOT_FOUND = "SESSION_NOTE_NOT_FOUND"
    SESSION_GOAL_FORBIDDEN = "SESSION_GOAL_FORBIDDEN"
    SESSION_GOAL_NOT_FOUND = "SESSION_GOAL_NOT_FOUND"

    # Review & Feedback Domain
    REVIEW_NOT_FOUND = "REVIEW_NOT_FOUND"
    REVIEW_NOT_ELIGIBLE = "REVIEW_NOT_ELIGIBLE"
    REVIEW_ALREADY_EXISTS = "REVIEW_ALREADY_EXISTS"
    REVIEW_FORBIDDEN = "REVIEW_FORBIDDEN"
    REVIEW_INVALID_RATING = "REVIEW_INVALID_RATING"
    REVIEW_HIDDEN = "REVIEW_HIDDEN"

    # Support Domain
    SUPPORT_TICKET_NOT_FOUND = "SUPPORT_TICKET_NOT_FOUND"
    SUPPORT_TICKET_FORBIDDEN = "SUPPORT_TICKET_FORBIDDEN"
    SUPPORT_TICKET_INVALID_STATE = "SUPPORT_TICKET_INVALID_STATE"
    SUPPORT_TICKET_REFERENCE_FORBIDDEN = "SUPPORT_TICKET_REFERENCE_FORBIDDEN"
    SUPPORT_MESSAGE_FORBIDDEN = "SUPPORT_MESSAGE_FORBIDDEN"
    SUPPORT_ASSIGNMENT_FORBIDDEN = "SUPPORT_ASSIGNMENT_FORBIDDEN"
    SUPPORT_ATTACHMENT_INVALID = "SUPPORT_ATTACHMENT_INVALID"

    # Operations, Admin & First Responder Domain
    OPS_FORBIDDEN = "OPS_FORBIDDEN"
    OPS_PERMISSION_REQUIRED = "OPS_PERMISSION_REQUIRED"
    OPS_RESOURCE_NOT_FOUND = "OPS_RESOURCE_NOT_FOUND"
    OPS_INVALID_OPERATION = "OPS_INVALID_OPERATION"
    OPS_ROLE_CHANGE_FORBIDDEN = "OPS_ROLE_CHANGE_FORBIDDEN"
    OPS_LEAD_NOT_FOUND = "OPS_LEAD_NOT_FOUND"
    OPS_LEAD_ALREADY_EXISTS = "OPS_LEAD_ALREADY_EXISTS"
